### ISSUE TITLE
soll und sold Alias besser in einanderes File

### ISSUE THREAD

**Issue by narwahls** [bse666/dotfiles#2]
Nachdem nun jedesml beim Login das urxvt in einem wunderschönen Pink erstrahlte habe ich etwas nachgeforscht wie man das ganze am besten Lösen kann.
Da die ZSH ieber die $HOME/.zprofile, als die $HOME/.profile, nutzen möchte, habe ich beide angelegt. Momentan gleich, kann sich die .zprofile später anders entwickeln.
Das ganze ist im Commit narwahls/configurations@a280d8a81446090bc84d1f5028702890f9395a4e  bei mir hinterlegt...
Vielleicht interessiert es dich ja.
Viele Grüße.

**Comment by bse666** [comment]
Das ist mir seit Herbstluft nicht mehr unter gekommen :smile: 
siehe 
https://github.com/bse666/dotfiles/blob/master/.config/herbstluftwm/autostart#L174

**Comment by narwahls** [comment]
Ja gut, das ist auch ne Lösung. Hatte mir das ganze halt nur als universelle Lösung abseits des wm überlegt. Hauptsache läuft XD

**Comment by bse666** [comment]
Hier vielleicht noch etwas interessantes zum weiterverwenden commit: 5884fb2dce1f777b60c06a0b72e63a5d2a480524
